In [4]:
%load_ext autoreload
%autoreload 2

# Tus imports de siempre abajo:
from src.ingesta.cargador import CargadorDatos
from src.eda.procesador import ProcesadorEDA

In [7]:
# Celda 1: Importaciones y carga

from IPython.display import display
from src.ingesta.cargador import CargadorDatos
from src.eda.procesador import ProcesadorEDA

cargador = CargadorDatos()
df_raw = cargador.descargar_y_filtrar_raw()

# Celda 2: Procesamiento
procesador = ProcesadorEDA(df_raw)
procesador.limpieza_datos()
df_procesado = procesador.generar_columnas_derivadas()
cargador.guardar_procesado(df_procesado)

# Celda 3: Resumen descriptivo
print("--- RESUMEN DESCRIPTIVO ---")
display(procesador.resumen_descriptivo()) # Ahora usará el display correcto

# Celda 4: Matriz de Correlación
print("--- MATRIZ DE CORRELACIÓN ---")
display(procesador.matriz_correlacion())

Descargando datos desde el repositorio de GitHub...
Filtrando partidos únicamente de la Copa Mundial de la FIFA...
Archivo raw guardado exitosamente en: ../data/raw/partidos-mundial.csv
Limpieza de datos completada.
Columnas derivadas agregadas exitosamente.
Archivo procesado guardado exitosamente en: ../data/processed/partidos-limpios.csv
--- RESUMEN DESCRIPTIVO ---

,date,home_score,away_score,anio,total_goles,diferencia_goles
count,1057,1057.000000,1057.000000,1057.000000,1057.000000,1057.000000
mean,1992-12-21 16:00:27.246925,1.568590,1.232734,1992.478713,2.801325,0.335856
min,1930-07-13 00:00:00,0.000000,0.000000,1930.000000,0.000000,-8.000000
25%,1974-07-03 00:00:00,0.000000,0.000000,1974.000000,1.000000,-1.000000
50%,1998-06-14 00:00:00,1.000000,1.000000,1998.000000,3.000000,0.000000
75%,2014-06-19 00:00:00,2.000000,2.000000,2014.000000,4.000000,1.000000
max,2026-07-06 00:00:00,10.000000,8.000000,2026.000000,12.000000,9.000000
std,NaN,1.501034,1.286861,25.187512,1.928720,2.024418

--- MATRIZ DE CORRELACIÓN ---

,home_score,away_score,anio,total_goles,diferencia_goles
home_score,1.000000,-0.048962,-0.137402,0.745586,0.772588
away_score,-0.048962,1.000000,-0.169504,0.629105,-0.671973
anio,-0.137402,-0.169504,1.000000,-0.220028,0.005870
total_goles,0.745586,0.629105,-0.220028,1.000000,0.152923
diferencia_goles,0.772588,-0.671973,0.005870,0.152923,1.000000